export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
// AUTH
export const ACCOUNT_AUTH_STATUS_CHANGED = 'ACCOUNT_AUTH_STATUS_CHANGED';
export const LOGIN_SUBMIT_USER_DATA = 'LOGIN_SUBMIT_USER_DATA';
export const LOGIN_SUBMIT_USER_OPERATOR_ID = 'LOGIN_SUBMIT_USER_OPERATOR_ID';
// Register
export const ACCOUNT_REGISTER_INIT = 'ACCOUNT_REGISTER_INIT';
export const ACCOUNT_REGISTER_SUBMIT_SUCCESS = 'ACCOUNT_REGISTER_SUBMIT_SUCCESS';
export const ACCOUNT_REGISTER_SUBMIT_FAILURE = 'ACCOUNT_REGISTER_SUBMIT_FAILURE';
// Login
export const ACCOUNT_LOGIN_INIT = 'ACCOUNT_LOGIN_INIT';
export const ACCOUNT_LOGIN_SUBMIT_SUCCESS = 'ACCOUNT_LOGIN_SUBMIT_SUCCESS';
export const ACCOUNT_LOGIN_SUBMIT_FAILURE = 'ACCOUNT_LOGIN_SUBMIT_FAILURE';
// Logout
export const ACCOUNT_LOGOUT_INIT = 'ACCOUNT_LOGOUT_INIT';
export const ACCOUNT_LOGOUT_SUBMIT_SUCCESS = 'ACCOUNT_LOGOUT_SUBMIT_SUCCESS';
export const ACCOUNT_LOGOUT_SUBMIT_FAILURE = 'ACCOUNT_LOGOUT_SUBMIT_FAILURE';

// Settings
export const ACCOUNT_SETTINGS_PASSWORD_SUBMIT_SUCCESS = 'ACCOUNT_SETTINGS_PASSWORD_SUBMIT_SUCCESS';
export const ACCOUNT_SETTINGS_PASSWORD_SUBMIT_FAILURE = 'ACCOUNT_SETTINGS_PASSWORD_SUBMIT_FAILURE';

export const NOTIFICATION_COUNTS_INIT = 'NOTIFICATION_COUNTS_INIT';


//常量
export  const  ACCESS_TOKEN="accessToken";
export  const  ACCESS_USER="accessUser";
export  const  TODAY_DATA="TODAY_DATA"



//药品进销存表格数据
export  const  MEDICINE_TABLE_DATA="MEDICINE_TABLE_DATA"
//审核表格title
export  const  AUDIT_TABLE_DATA_TITLE="AUDIT_TABLE_DATA_TITLE"
//审核表格content
export  const  AUDIT_TABLE_DATA_CONTENT="AUDIT_TABLE_DATA_CONTENT"
//添加商品data
export  const  MEDICINE_ADD_GOODS="MEDICINE_ADD_GOODS"
//选择商品data
export  const  MEDICINE_SELECT_GOODS="MEDICINE_SELECT_GOODS"
//删除商品data
export  const  MEDICINE_SELECT_DELETE_GOODS="MEDICINE_SELECT_DELETE_GOODS"
//选择商品的下标
export  const  AUDIT_TABLE_SELECTED_INDEX="AUDIT_TABLE_SELECTED_INDEX"
//删除商品data
export  const  MEDICINE_COMPILE_SUPPLIERS_NO="MEDICINE_COMPILE_SUPPLIERS_NO"
export  const  MEDICINE_COMPILE_USER_ID="MEDICINE_COMPILE_USER_ID"

//收费
export  const  SHOW_PHYSIQUE_USER_DATA="SHOW_PHYSIQUE_USER_DATA"
export  const  SHOW_PHISICAL_DATA="SHOW_PHISICAL_DATA"
export  const  SHOW_CHARGE_DATA="SHOW_CHARGE_DATA"
export  const  IS_CHARGE_DATA="IS_CHARGE_DATA"

//获得待发药传递参数
export  const  SHOW_REGISTEREDORDID="SHOW_REGISTEREDORDID";
//设置模板内容
export  const  SET_TEMPLATE_CONTENT="SET_TEMPLATE_CONTENT";
//主诉内容
export  const  SET_CHIEF_COMPLAINT="SET_CHIEF_COMPLAINT";
//初步诊断
export  const  SET_PRELIMINARY_DIAGNOSIS="SET_PRELIMINARY_DIAGNOSIS";
//设置模板类型
export  const  SET_TEMPLATE_CONTENT_TYPE="SET_TEMPLATE_CONTENT_TYPE";

//审核
export  const  SHOW_STOCK_OSTOCKTYPE="SHOW_STOCK_OSTOCKTYPE"
export  const  SHOW_STOCK_OSTOCKID="SHOW_STOCK_OSTOCKID"