/**
 * Created by imac on 17/2/27.
 */
export  default {
  add_goods:"add_goods",
  registeredOrdId:"registeredOrdId",
  USER_NATION_ARR:"USER_NATION_ARR",//民族
  DOSAGE_FORM:"DOSAGE_FORM",//剂型
  USAGE_TYPE:"USAGE_TYPE",//药品用法
  PROD_FREQUENCY:"PROD_FREQUENCY",//用药频次
  PROD_UNIT:"PROD_UNIT",//商品单位
  CLINIC_TYPE:"CLINIC_TYPE",//诊所类型
  REGISTERED_TYPE:"REGISTERED_TYPE",//接诊类型
  PROD_TYPE:"PROD_TYPE",//商品类型
  USER_SEX:"USER_SEX",//性别类型
  ALLERGY_THING:"ALLERGY_THING",//过敏源
  ALLERGY_REACTION:"ALLERGY_REACTION",//过敏反应
  ALLERGY_DEGREE:"ALLERGY_DEGREE",//过敏程度
  AUTH_ACCESS_USER_OPERATOR_ID:"AUTH_ACCESS_USER_OPERATOR_ID",
  AUTH_ACCESS_USER_OPERATOR_NAME:"AUTH_ACCESS_USER_OPERATOR_NAME",
  AUTH_ACCESS_USER_BILLID:"AUTH_ACCESS_USER_BILLID",
}
